version: '1'
  services:
    flask:
      container_name: flask
      image: aleksinyyss/doge:latest
      command: python /app/server.py
      restart: always
      ports:
      - "80:80"
    doge:
      container_name: doge
      image: aleksinyyss/doge:latest
      command: python /app/doge.py

      environment:
        - DOGE_TOKEN
      volumes:
        - /mp3:/app/mp3
