version: '2'
services:
  flask:
    container_name: flask
    image: aleksinyyss/doge:latest
    command: python server.py
    restart: always
    volumes:
      - ./root/mp3:/app/mp3
    ports:
    - "80:80"
  doge:
    container_name: doge
    image: aleksinyyss/doge:latest
    command: python doge.py
    restart: always
    environment:
      - DOGE_TOKEN
    volumes:
      - ./root/mp3:/app/mp3

volumes:
  mydata: